AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploys the GetVolatility Lambda function'

Parameters:
  LambdaCodeKey:
    Type: String
    Description: 'S3 key for the Lambda deployment package'

Resources:
  # S3 Bucket to store Lambda code
  LambdaCodeBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'get-volatility-lambda-code-bucket'  # You can change this name to fit your requirements
      VersioningConfiguration:
        Status: Enabled  # Optional: Enable versioning for your S3 bucket

  # Lambda Function
  GetVolatilityLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: 'lambda_function.lambda_handler'  # Ensure this matches your actual handler
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: 'GetVolatilityFunction'
      Runtime: 'python3.10'  # Ensure this matches your runtime
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      MemorySize: 128
      Timeout: 5

  # IAM Role for Lambda Execution
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action: 'sts:AssumeRole'
            Principal:
              Service: 'lambda.amazonaws.com'
      Policies:
        - PolicyName: 'LambdaExecutionPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'

Outputs:
  LambdaFunctionArn:
    Description: 'ARN of the GetVolatility Lambda function'
    Value: !GetAtt GetVolatilityLambda.Arn

  LambdaCodeBucketName:
    Description: 'The name of the S3 bucket where Lambda code is stored'
    Value: !Ref LambdaCodeBucket
