version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies for the frontend app..."
      - cd frontend/app
      - npm install

  build:
    commands:
      - echo "Building the Next.js application..."
      - npm run build

artifacts:
  files:
    - '**/*'   # Include all built files in the `.next` folder
  base-directory: frontend/app
