version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies for the frontend app..."
      - cd frontend/app
      - npm install

  build:
    commands:
      - echo "Building the Next.js application..."
      - npm run build
      - echo "Exporting the Next.js application to static files..."
      - npm run export

artifacts:
  files:
    - 'out/**/*'  # The `next export` command generates files in the `out` directory by default
  base-directory: frontend/app
