version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Zipping Lambda function..."
      - mkdir -p /tmp/lambda-package
      - cp -r backend_app/src/stocks/volatility_fetch/app/* /tmp/lambda-package/
      - cd /tmp/lambda-package && zip -r /tmp/getVolatility.zip .
      - cd -
      - echo "Creating S3 bucket if it does not exist..."
      - aws s3api head-bucket --bucket lambda-cf || aws s3 mb s3://lambda_cf
      - echo "Uploading Lambda package to S3..."
      - aws s3 cp /tmp/getVolatility.zip s3://lambda-cf/lambda-code/getVolatility.zip
  post_build:
    commands:
      - echo "Deploying Lambda stack..."
      - aws cloudformation deploy \
          --stack-name lambda-stack \
          --template-file infra/cloudformation/lambda.yaml \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides CodeBucket=lambda-cf LambdaCodeKey=lambda-code/getVolatility.zip
