#!/usr/bin/env node

/**
 * Generate Runtime Configuration Script
 * This script generates config.js with real values from Terraform outputs
 * Used by the deployment pipeline to create dynamic configuration
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Template for config.js
const CONFIG_TEMPLATE = `// Runtime Configuration
// This file is dynamically generated by the deployment pipeline
// and can be updated without rebuilding the application

window.COSINE_CONFIG = {
  // API Configuration
  apiGatewayUrl: '{{API_GATEWAY_URL}}',
  websocketUrl: '{{WEBSOCKET_URL}}',
  awsRegion: '{{AWS_REGION}}',
  
  // Environment
  environment: '{{ENVIRONMENT}}',
  
  // Cognito Configuration (if using auth)
  cognitoUserPoolId: '{{COGNITO_USER_POOL_ID}}',
  cognitoClientId: '{{COGNITO_CLIENT_ID}}',
  cognitoDomain: '{{COGNITO_DOMAIN}}',
  
  // Redirect URLs
  redirectSignIn: '{{REDIRECT_SIGN_IN}}',
  redirectSignOut: '{{REDIRECT_SIGN_OUT}}',
  
  // Build timestamp for cache busting
  buildTimestamp: '{{BUILD_TIMESTAMP}}',
  
  // Version info
  version: '{{VERSION}}',
  commitSha: '{{COMMIT_SHA}}'
};

// Helper function to get config with fallbacks
window.getConfig = function(key, defaultValue = null) {
  return window.COSINE_CONFIG[key] || defaultValue;
};

// Helper function to check if config is loaded
window.isConfigLoaded = function() {
  return window.COSINE_CONFIG && window.COSINE_CONFIG.apiGatewayUrl !== '{{API_GATEWAY_URL}}';
};

console.log('🔧 Runtime configuration loaded:', window.COSINE_CONFIG);
`;

function generateConfig(options = {}) {
  const {
    apiGatewayUrl = '',
    websocketUrl = '',
    awsRegion = 'us-east-1',
    environment = 'development',
    cognitoUserPoolId = '',
    cognitoClientId = '',
    cognitoDomain = '',
    redirectSignIn = '',
    redirectSignOut = '',
    buildTimestamp = new Date().toISOString(),
    version = '1.0.0',
    commitSha = process.env.GITHUB_SHA || 'local'
  } = options;

  // Replace placeholders with real values
  let config = CONFIG_TEMPLATE
    .replace(/{{API_GATEWAY_URL}}/g, apiGatewayUrl)
    .replace(/{{WEBSOCKET_URL}}/g, websocketUrl)
    .replace(/{{AWS_REGION}}/g, awsRegion)
    .replace(/{{ENVIRONMENT}}/g, environment)
    .replace(/{{COGNITO_USER_POOL_ID}}/g, cognitoUserPoolId)
    .replace(/{{COGNITO_CLIENT_ID}}/g, cognitoClientId)
    .replace(/{{COGNITO_DOMAIN}}/g, cognitoDomain)
    .replace(/{{REDIRECT_SIGN_IN}}/g, redirectSignIn)
    .replace(/{{REDIRECT_SIGN_OUT}}/g, redirectSignOut)
    .replace(/{{BUILD_TIMESTAMP}}/g, buildTimestamp)
    .replace(/{{VERSION}}/g, version)
    .replace(/{{COMMIT_SHA}}/g, commitSha);

  return config;
}

function writeConfigFile(config, outputPath) {
  // Resolve under cwd and reject path traversal (Semgrep: path-join-resolve-traversal)
  const base = process.cwd();
  const fullPath = path.resolve(base, path.normalize(outputPath));
  const relative = path.relative(base, fullPath);
  if (relative.startsWith('..') || path.isAbsolute(relative)) {
    throw new Error('Invalid output path: must stay within project');
  }
  const dir = path.dirname(fullPath);

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(fullPath, config);
  console.log('✅ Runtime configuration written to:', fullPath);
}

// CLI usage
if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  
  if (args.includes('--help') || args.includes('-h')) {
    console.log('Generate Runtime Configuration Script');
    console.log('');
    console.log('Usage:');
    console.log('  node scripts/generate-config.js [options]');
    console.log('');
    console.log('Options:');
    console.log('  --api-gateway-url <url>     API Gateway URL from Terraform');
    console.log('  --aws-region <region>       AWS Region (default: us-east-1)');
    console.log('  --environment <env>         Environment (development/staging/production)');
    console.log('  --cognito-user-pool-id <id> Cognito User Pool ID');
    console.log('  --cognito-client-id <id>    Cognito Client ID');
    console.log('  --cognito-domain <domain>   Cognito Domain');
    console.log('  --redirect-sign-in <url>    Sign In Redirect URL');
    console.log('  --redirect-sign-out <url>   Sign Out Redirect URL');
    console.log('  --output <path>             Output path (default: public/config.js)');
    console.log('');
    console.log('Example:');
    console.log('  node scripts/generate-config.js \\');
    console.log('    --api-gateway-url "https://abc123.execute-api.us-east-1.amazonaws.com/staging" \\');
    console.log('    --environment staging \\');
    console.log('    --aws-region us-east-1');
    process.exit(0);
  }
  
  // Parse command line arguments
  const options = {};
  let outputPath = 'public/config.js';
  
  for (let i = 0; i < args.length; i += 2) {
    const key = args[i];
    const value = args[i + 1];
    
    if (key === '--api-gateway-url') options.apiGatewayUrl = value;
    else if (key === '--websocket-url') options.websocketUrl = value;
    else if (key === '--aws-region') options.awsRegion = value;
    else if (key === '--environment') options.environment = value;
    else if (key === '--cognito-user-pool-id') options.cognitoUserPoolId = value;
    else if (key === '--cognito-client-id') options.cognitoClientId = value;
    else if (key === '--cognito-domain') options.cognitoDomain = value;
    else if (key === '--redirect-sign-in') options.redirectSignIn = value;
    else if (key === '--redirect-sign-out') options.redirectSignOut = value;
    else if (key === '--output') outputPath = value;
  }
  
  // Generate and write config
  const config = generateConfig(options);
  writeConfigFile(config, outputPath);
}

export { generateConfig, writeConfigFile };
